cache:
  - C:\projects\go
environment:
  GOPATH: C:\projects\go
install:
  - if exist C:\projects\go\src\github.com\douglaswth\rsrdp (rmdir /s /q C:\projects\go\src\github.com\douglaswth\rsrdp)
  - xcopy . C:\projects\go\src\github.com\douglaswth\rsrdp /i
  - go get -t -v ./...
build_script:
  - go build -v ./...
test_script:
  - go test -v -cover ./...
artifacts:
  - path: rsrdp.exe
