cache:
  - C:\projects\go
environment:
  GOPATH: C:\projects\go
install:
  - rmdir /s /q C:\projects\go\src\github.com\douglaswth\rsrdp
  - xcopy . C:\projects\go\src\github.com\douglaswth\rsrdp /i
  - cd C:\projects\go\src\github.com\douglaswth\rsrdp & go get -t -v ./...
build_script:
  - cd C:\projects\go\src\github.com\douglaswth\rsrdp & go build -v ./...
test_script:
  - cd C:\projects\go\src\github.com\douglaswth\rsrdp & go test -v -cover ./...
artifacts:
  - path: C:\projects\go\src\github.com\douglaswth\rsrdp\rsrdp.exe
