clone_folder: C:\projects\go\src\github.com\douglaswth\rsrdp
environment:
  GOPATH: C:\projects\go
install:
  - appveyor SetVariable -Name PATH -Value "%GOPATH%\bin;%PATH%;C:\Ruby21-x64\DevKit\mingw\bin"
  - go get -t -v -d ./...
build_script:
  - go install -v ./...
after_build:
  - 7z a rsrdp.zip %GOPATH%\bin\rsrdp.exe %GOPATH%\bin\rsrdp-run.exe
test_script:
  - go test -v -cover ./...
artifacts:
  - path: rsrdp.zip
